---
ws_port: 20102
ws_keymode: AES-128
server_name: kshdskahdksajdhah
http_port: 20103
sqlmode: sqlite3
def_money_name: 贡献点
def_money_number: 0
whitelist: true
delplayer: 4
addplayer: 4
delplme: false
getplall: 50
