name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cross
      run: cargo install cross
    - name: Build for Linux
      run: cross build --target x86_64-unknown-linux-gnu --release
    - name: Package for Linux
      run: cross package --target x86_64-unknown-linux-gnu --release
    - name: Build for Windows
      run: cross build --target x86_64-pc-windows-gnu --release
    - name: Package for Windows
      run: cross package --target x86_64-pc-windows-gnu --release
